### PR TITLE
Remove unnecessary branches in recursion.

### PR DESCRIPTION
**Pull request by egeyar**
I am using rusty-tags on a very large source base. As the base grew, rusty-tags started to require too much resources and eventually to hang. I looked into the source code and identified places to improve the performance. The tags that are created by the resulting binary seems to be functioning well according to a short experiment.

Before this patch, killed by ctrl-C after an hour:
egeyar@oberland:~/repos/dfinity/rs$ time  /home/egeyar/repos/rusty-tags/target/debug/rusty-tags --num-threads=1  vi
Fetching source and metadata ...
^C
real    62m6.178s
user    62m2.417s
sys     0m0.513s

egeyar@oberland:~/repos/dfinity/rs$

After this patch, completed under 40 seconds:
egeyar@oberland:~/repos/dfinity/rs$ time  /home/egeyar/repos/rusty-tags/target/debug/rusty-tags --num-threads=1  vi
Fetching source and metadata ...
Creating tags for: <some 107 crates in the project> ...

real    0m39.201s
user    0m38.261s
sys     0m0.894s

egeyar@oberland:~/repos/dfinity/rs$

### CODE REVIEW

**Comment by dan-t** [comment]
I looked into the implementation and I think, that I might have found a better fix for your issue.
Can you please test the 'dep_tree_perf_fix' branch.

**Comment by dan-t** [comment]
I think that I just added another optimization. Please test!

**Comment by egeyar** [comment]
egeyar@oberland:~/repos/dfinity/rs$ time  /home/egeyar/repos/rusty-tags/target/debug/rusty-tags --num-threads=1  vi
Fetching source and metadata ...
Creating tags for: <sources> ...

real	0m19.907s
user	0m18.285s
sys	0m0.758s

and the tags seem sane.

**Comment by dan-t** [comment]
How long does it take for the release version?

**Comment by egeyar** [comment]
As you can see above in the PR description, I killed the process (3.8.1) yesterday after waiting for an hour.

Inspecting with gdb suggested that it kept calling "compute_depths_internal". After I made the change to it that you see in this PR, it printed "Creating tags for: <my_sources>" , but still kept going until I killed the process. Then I modified "ancestors_internal" and got it down to 38 seconds as you see in the PR description.

**Comment by dan-t** [comment]
I think you misunderstood my question. How long does the release build of the dep_tree_perf_fix branch take? And also how long does it take without the one thread restriction?

**Comment by egeyar** [comment]
Ah I see. Here are the times from the second time I ran them to discard potential page miss differences between them:
egeyar@oberland:~/repos/dfinity/rs$ time  /home/egeyar/repos/rusty-tags/target/release/rusty-tags --num-threads=1  vi
Fetching source and metadata ...
Creating tags for: ...

eal	0m3.065s
user	0m2.510s
sys	0m0.502s
egeyar@oberland:~/repos/dfinity/rs$ time  /home/egeyar/repos/rusty-tags/target/release/rusty-tags  vi
Fetching source and metadata ...
Creating tags for: ...

real	0m2.971s
user	0m2.501s
sys	0m0.416s
egeyar@oberland:~/repos/dfinity/rs$

**Comment by dan-t** [comment]
rusty-tags 3.9.0 is now released including these optimizations.

**Pull request closed without merging**
