### PR TITLE
Fix move_tags error on different filesystems

### PR DESCRIPTION
**Pull request by redhat008**
As the title.  
If RUST_SRC_PATH and HOME on different filesystems. rusty-tags will return other os  error because of the std:fs::rename funtion.

rename  function will return an error in the following situations, but is not limited to just these cases:

from does not exist.
The user lacks permissions to view contents.
from and to are on separate filesystems.

https://doc.rust-lang.org/std/fs/fn.rename.html

### CODE REVIEW

**Comment by dan-t** [comment]
On Fri, Apr 07, 2017 at 11:56:33PM -0700, redhat008 wrote:
> If RUST_SRC_PATH and HOME on different filesystems. rusty-tags will return
> other os error because of the std:fs::rename funtion.

It should be ensured that a move is only done on the same file system,
by having a separate temporary directory for `$RUST_SRC_PATH`,
`$CARGO_HOME` and `~/.rusty-tags`, and only moving from this
temporary directory to the final destination.

Moving a file instead of copying it, is a correctness property, to
ensure that multiple running `rusty-tags` don't trash the tags file
of each other.

I don't understand how in your case a file from `$RUST_SRC_PATH` should
be moved to `$HOME`. It should be only moved from the temporary directory
below `$RUST_SRC_PATH` to `$RUST_SRC_PATH`.

Please show me the exact paths being moved.

**Comment by redhat008** [comment]
Sorry i did not describe it the details clearly.

I run the rusty-tags on Windows.  I install rust and rust src from the rustup command in the C drive.  so cargo install rusty-tags.exe on C:\.

I installed cygwin. So I set HOME="E:\gxx"

Then I run "rusty-tag.exe -v vi"  for the tikv project (E:\gxx\rust\tikv). 

Creating tags for 'tikv' ...

Creating tags ...
   for source:
      C:\Users\redhat008\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.16\src

   cached at:
      E:\gxx\rust\tikv\source-temp-dir.Fe3aj5VTONf3\src_tags

Copy tags ...
   from:
      E:\gxx\rust\tikv\source-temp-dir.Fe3aj5VTONf3\src_tags
   to:
      E:\gxx\.rusty-tags\cache\cache-temp-dir.ZfjQzTniNMDc\cached_tags

Move tags ...
   from:
      E:\gxx\.rusty-tags\cache\cache-temp-dir.ZfjQzTniNMDc\cached_tags
   to:
      E:\gxx\.rusty-tags\cache\libc-8116036112051344268.vi

Copy tags ...
   from:
      E:\gxx\rust\tikv\source-temp-dir.Fe3aj5VTONf3\src_tags
   to:
      E:\gxx\.cargo\cargo-temp-dir.bRyLj921QGIg\cargo_tags

Move tags ...
   from:
      E:\gxx\.cargo\cargo-temp-dir.bRyLj921QGIg\cargo_tags
   to:
      C:\Users\redhat008\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.16\.tags
The system cannot move the file to a different disk drive. (os error 17).

**Comment by dan-t** [comment]
This seems to be an issue related to cygwin.

> Move tags ...
> from:
> E:\gxx.cargo\cargo-temp-dir.bRyLj921QGIg\cargo_tags
> to:
> C:\Users\redhat008.cargo\registry\src\github.com-1ecc6299db9ec823\
> libc-0.2.16.tags
> The system cannot move the file to a different disk drive. (os error 17).

It seems that `rusty-tags` thinks that the cargo home is at `E:\gxx.cargo`,
but its real home is located at `C:\Users\redhat008.cargo`.

I don't know how `rusty-tags` should detect this. cargo seems to get the
home directory in an other way and ignores the cygwin one.

If you're setting the environment variable `CARGO_HOME=C:\Users\redhat008.cargo`
it most likely will work.

**Comment by redhat008** [comment]
Yes. it work. You're right.  I'm setting the environment variable `CARGO_HOME=C:\Users\redhat008\\.cargo`

**Pull request closed without merging**
