### PR TITLE
Update and relax the dependencies on toml & dirs

### PR DESCRIPTION
**Pull request by sylvestre**
I don't think the minor needs to be hardcoded

### CODE REVIEW

**Comment by dan-t** [comment]
What is the motivation for the change?

**Comment by sylvestre** [comment]
The packaging of rusty-tags in Debian & Ubuntu.
rusty-tags uses packages available in the Debian archive. We have now more recent version of dirs & toml. (caused https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946019 )
Also, hardcoding to exact versions makes the life of packagers much harder.
We can expect that minor releases of crates are stable enough than we can relax the dep.

**Comment by dan-t** [comment]
> We can expect that minor releases of crates are stable enough than we can relax the dep.

But according to the semantic versioning scheme used by crates.io, you didn't just remove the minor versions. That would have been `toml = "~0.4"` and `dirs = "1.0.4"`. With your change it can't be build anymore with `toml 0.4` and `dirs 1.0`.

**Comment by dan-t** [comment]
Sorry, I meant `toml = "~0.4"` and `dirs = "~1.0"`.

**Comment by sylvestre** [comment]
Indeed, my goal was to use more recent version of dirs & toml by default
but happy to relax the dep if you want

**Comment by dan-t** [comment]
I don't see a need for forcing a newer version if there's no need for it. I also don't understand why you removed the minor versions only for these two dependencies?

But there's also a point about minor versions, because adding e.g. a function - as much as I know - isn't considered a breaking change. So if you depend on a function being added by the minor version "0.4.2", then it wouldn't build with "0.4".

But yes, a minor version like "1.0.4" most likely doesn't add anything.

So, in which way does this change make the life of a package maintainer easier? Because if debian supports newer versions of these dependencies, than it should just build with the current versions, right?

**Comment by dan-t** [comment]
> Because if debian supports newer versions of these dependencies, than it should just build with the current versions, right?

Sorry, I've been wrong about this. For a moment I thought the versions are minimal versions, which isn't the case. So I think the change you want is more something like `toml = ">= 0.4.10, < 0.6"`, right?

**Comment by sylvestre** [comment]
> So, in which way does this change make the life of a package maintainer easier? Because if debian supports newer versions of these dependencies, than it should just build with the current versions, right?

First, I should have separate this PR into two.

1) Relax the minor version 1.0.4 => ~1.0
2) Upgrade to the next major version

Sorry about the confusion I added here.

Now, doing toml = ">= 0.4.10, < 0.6", can be done too, sure, as manager, you make a call on this as you might have bugs in 0.4.X that could be fixed in 0.5.

is it more clear?

**Comment by dan-t** [comment]
Ok, thinking about the whole thing a bit, I think I'm fine with your
increase of the versions. There're only two ways how people will get/use
`rusty-tags`: building it with `cargo install` or by getting it from
their package manager, and both cases shouldn't be impaired by
a version increase.

The default for dependencies - if neither `~` nor `^` is specified - is
`^`, which from the semantic versioning viewpoint is the better one.

So just remove the `~` and I'm fine with your change.

**Comment by dan-t** [comment]
Args, I just saw that your change doesn't build with `rustc 1.24.1`, which I added to ensure
to stay compatible with debian.

Your change is for a newer debian version, right? So which version of `rustc` does it use?
Could you please change the rustc version in `.travis.yml`  accordingly.

**Pull request merged**
