### PR TITLE
Add command line option to set tags filename

### PR DESCRIPTION
**Pull request by jhand2**
Adds an option to set the output filename from the command line rather than needing to use a global config file.

To support this, removes the restriction and vi and emacs filenames can't be the same. From a config file perspective I think the user can be trusted to understand the consequences of naming the files the same thing.

### CODE REVIEW

**Comment by dan-t** [comment]
I won't remove the restriction. It's not about trust, it's about ensuring that tags for
vi and emacs can be used at the same time, and it just works.

Only allowing the rename in the config file makes it easier to ensure this.

**Comment by jhand2** [comment]
What if instead I enforce the check when the config file is read, around line 68 in config.rs.

Then you can't use the same name in the config file, but at command line time the user can pass whatever they want at command line.

I understand if you still disagree but this could be a happy medium.

**Comment by dan-t** [comment]
What is you main motivation for having a different tags file name?

**Comment by jhand2** [comment]
For the most part in rust-only projects I want to use the default ctags 'tags' filename. It will just work with many configurations like default .gitignore files, various .vimrc files across different machines. So whatever configuration I'm working on, I can just do `rusty-tags -O tags`.

However, with projects with both rust and C, I would want to use a different filename, since I would be using ctags to generate a `tags` file for C. So being able to make that filename decision differently for different projects rather than having a global configuration in my home directory.

Adding this option doesn't take anything away from using a config file (as long as a add back the same filename check like a mentioned), it just makes usage from the command line more flexible.

**Comment by dan-t** [comment]
> What if instead I enforce the check when the config file is read, around line 68 in config.rs.
> 
> Then you can't use the same name in the config file, but at command line time the user can pass whatever they want at command line.
> 
Keep the check, only change the tags name of the current TagsKind and
use just ˋoutputˋ as the long option name, then I think it is fine.

But you are aware that without setting ˋset tagsˋ in the vimrc, you will not get tags for the std library? Perhaps it would be better to just always merge the std tags into the cargo project tags.

**Comment by jhand2** [comment]
Ok I'm good with that. Will update in a few hours.

As for merging the stdlib tags, I do think it would make things more portable. Also keeps rust source directory clean. As long as the stdlib tags file isn't huge I think its fine to merge them into each project's tags file.

**Comment by jhand2** [comment]
Alright updated my branch. Are you able to reopen this PR or would you like me to create a new one?

**Comment by dan-t** [comment]
> Alright updated my branch. Are you able to reopen this PR or would you like me to create a new one?
> 
Please cleanup the change into one commit and open a new PR.

**Comment by dan-t** [comment]
> As for merging the stdlib tags, I do think it would make things more portable. Also keeps rust source directory clean. As long as the stdlib tags file isn't huge I think its fine to merge them into each project's tags file.
> 
The problem is, that the tags for every dependencies would also need to include
the tags for the std, otherwise you would not be able to jump to the std from
the source of a dependency.

Also by changing the used compiler the std tags will not update, which currently also
just works.

So all in all, merging makes things just worse.

**Pull request closed without merging**
