### PR TITLE
Used clap to simplify command line argument parsing

### PR DESCRIPTION
**Pull request by kbknapp**
@dan-t 
If you're interested I added clap to do the argument parsing for you. This simplifies the start-up as you don't have have to do any error handling or usage statements. It also gives you the help/version flags for free. 

To see what I mean, build and run:
```
$ rusty-tags wrong
"wrong" isn't a valid value for MODE
        [valid values: vi emacs]
USAGE:
        rusty-tags [FLAGS]  <MODE>  
For more information try --help
$ rusty-tags vi
[... your output ...]
```
I know it's not really needed just to parse a single argument, but in the event you want to add options in the future this simplifies it quite a bit.

No pressure to include if you're not interested, just thought I'd throw it out there ;)

Edit: Forgot to add at-mention :P

### CODE REVIEW

**Comment by dan-t** [comment]
Thanks! For now I just want to keep the dependencies low until Rust 1.0 is out.

If Rust 1.0 is out I will have another look.

**Comment by kbknapp** [comment]
No worries, thanks for the look :)

**Comment by Anachron** [comment]
Rust 1.0 is out ;)

**Comment by dan-t** [comment]
Thanks! It's now part of rusty-tags 0.4.1.

**Pull request merged**
