### PR TITLE
tags: Fix `move_tags` for paths on separate filesystems

### PR DESCRIPTION
**Pull request by nfnty**

### CODE REVIEW

**Comment by dan-t** [comment]
What's your issue?

Is your $CARGO_HOME directory on an other filesystem than your
source code you're creating the tags for?

File moving is used to ensure the correctness for multiple
at once running rusty-tags programms, so changing it
to copying isn't an option.

There's already a temporary directory used for the tags
creation. So the correct solution would be to have a temporary
directory for each filesystem, which most likely means
on for your source code, one for $CARGO_HOME and another
for $RUST_SRC_PATH.

**Comment by nfnty** [comment]
The issue is:
```
Move tags ...
   from:
      /data/downloads/rusty-tags/rusty-tags-temp-dir.1lkHT17PFjAA/cached_tags
   to:
      /home/nfnty/.rusty-tags/cache/ansi_term-0.8.0.vi
Invalid cross-device link (os error 18)
```

Where `/data` and `/home` are different file systems.

I can see that I forgot to remove the copied file, but how is `rename` used to ensure correctness?

**Comment by dan-t** [comment]
> The issue is:
> 
> Move tags ...
>    from:
>       /data/downloads/rusty-tags/rusty-tags-temp-dir.1lkHT17PFjAA/cached_tags
>    to:
>       /home/nfnty/.rusty-tags/cache/ansi_term-0.8.0.vi
> Invalid cross-device link (os error 18)
So you're running rusty-tags from the directory where you have cloned
the rusty-tags repository? Why? Do you want tags for its source?

Moving/renaming is an atomic operation on the same filesystem, so
multiple at once running rusty-tags won't be able to write into the same file.

**Comment by nfnty** [comment]
Indeed, used `rusty-tags` as demonstration. Same thing happens for all projects.

That is not how `rename` atomicity works. From `rename(2)`:
```
If newpath already exists, it will be atomically replaced, so that there is no point at which another process attempting to access newpath  will  find  it  missing.
However, there will probably be a window in which both oldpath and newpath refer to the file being renamed.
```

**Comment by dan-t** [comment]
> However, there will probably be a window in which both oldpath and
> newpath refer to the file being renamed.

I can't follow. 'oldpath' is always under the control of the running
rusty-tags instance. Every instance has a unique temporary directory
where the 'oldpath' is located.

The tags are created at 'oldpath' and then renamed, at this point
nobody can hold/access the file at 'oldpath'.

If a running process has the file at 'newpath' opened, then the
OS keeps this file "alive" as long as processes have a handle to it,
but after the rename other processes will get the new file at 'newpath'.

rusty-tags itself never reads from 'newpath'.

**Comment by dan-t** [comment]
I just commited changes that should solve the issue.

Can you please check the current version in the git repository?

**Comment by nfnty** [comment]
> 'oldpath' is always under the control of the running rusty-tags instance. Every instance has a unique temporary directory where the 'oldpath' is located.

Then I understand what you mean. That will work just fine. But that is very different from:

> multiple at once running rusty-tags won't be able to write into the same file.

> The tags are created at 'oldpath' and then renamed, at this point nobody can hold/access the file at 'oldpath'.

Which is not true. `rename` has a race condition window where both paths refer to the same inode. But after that window, yes it's not possible to access the inode via `oldpath`.

> If a running process has the file at 'newpath' opened, then the OS keeps this file "alive" as long as processes have a handle to it, but after the rename other processes will get the new file at 'newpath'.

Yes, that is the atomicity that `rename` provides. `newpath` will always only refer to the last inode.

**Comment by nfnty** [comment]
The issue is fixed now, thanks.

**Pull request closed without merging**
