### PR TITLE
Add Emacs configuration info

### PR DESCRIPTION
**Pull request by redguardtoo**
as title

### CODE REVIEW

**Comment by dan-t** [comment]
Thanks!

Is counsel-etags the standard emacs way of using tags? Isn‘t there some out of the box emacs support for tags?

**Comment by redguardtoo** [comment]
There are tow most two popular ways:
 
One is using helm  (https://github.com/emacs-helm/helm/blob/master/helm-tags.el)

One is counsel-etags using `counsel/ivy` As I know, `counsel-etags` is the first plugin to support rusty-tags. See https://github.com/redguardtoo/counsel-etags/issues/42

**Comment by dan-t** [comment]
The configuration doesn't consider the rust std tags under `$RUST_SRC_PATH/rusty-tags.emacs`, right?

Can you please extend the configuration to consider these tags if they're available.

**Comment by redguardtoo** [comment]
I could make `counsel-etags-extra-tags-files` support environment variable.

**Comment by dan-t** [comment]
On Mon, May 20, 2019 at 01:27:09AM -0700, Chen Bin wrote:
> I could make counsel-etags-extra-tags-files support environment variable.

That would be great! Could you please then update the `rusty-tags` README. Thanks!

**Comment by redguardtoo** [comment]
@dan-t , see https://github.com/redguardtoo/counsel-etags/commit/02abc5dc794a912af37a176fb7bf635ce28e93fa 

I also sent you new README pull request.

**Comment by i-schuetz** [comment]
Can you please explain for people new to tags what you mean with "Add manually"? I got the source and set exported `RUST_SRC_PATH` in `~/.profile`. And now?

**Comment by dan-t** [comment]
> Can you please explain for people new to tags what you mean with "Add manually"? I got the source and set exported RUST_SRC_PATH in ~/.profile. And now?


The tags file rusty-tags.emacs of a cargo project, which lies beside of the Cargo.toml file of the cargo project, doesn’t contain the tags for the rust standard library, these are contained in $RUST_SRC_PATH/rusty-tags.emacs.

Normally you will configure your editor in a way that it automatically finds the tags of the cargo project, but you have to ensure that it also searches under $RUST_SRC_PATH.

The example configuration of counsel-etags in the README already does this.

**Comment by i-schuetz** [comment]
@dan-t Thanks! I created `.dir-locals.el` and so far `M-x counsel-etags-find-tag-at-point` works for both my files and the standard library. The navigation with shortcut is still not working properly though: If I navigate to one of my items, it asks for the tags file location. I enter the path to the file that was generated by `rusty-tags emacs` (which as far I can see contains only the tags for my project). After this, it's (as expected) able to navigate only to my items. If I try to navigate to a standard library item it will say "no match". How do I setup the shortcut navigation such that it works for both my and the standard library items?

**Comment by dan-t** [comment]
> How do I setup the shortcut navigation such that it works for both my and the standard library items?


I’m sorry, I don’t use emacs, so I can’t help here. Please ask the counsel-etags developers.

**Pull request merged**
